### PR TITLE
Implements Reverse DNS lookup based on netbox

### PR DESCRIPTION
**Pull request by kotso**
handles PTR requests as discussed here: https://github.com/oz123/coredns-netbox-plugin/issues/34

### CODE REVIEW

**Comment by kotso** [comment]
Fix linter issue

**Comment by oz123** [comment]
Thanks for the PR. Already looking good, can you add a test case for that?

**Comment by kotso** [comment]
added tests also

**Comment by jdoss** [comment]
Can this get merged? I'd love to have this feature in this plugin.

**Comment by oz123** [comment]
Sorry for the late response. Hint: sponsor for faster response. I'm busy with work and life. Sorry.

**Review by oz123 — APPROVED** [review]

**Comment by jdoss** [comment]
Thank you @oz123!

**Pull request merged**
